version: '3.8'

services:
  # MariaDB Database for local development
  mariadb:
    image: mariadb:11.2
    container_name: hikehub-mariadb
    environment:
      MARIADB_DATABASE: organiser_platform
      MARIADB_USER: organiser_user
      MARIADB_PASSWORD: organiser_pass
      MARIADB_ROOT_PASSWORD: root
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
