version: '3.8'

services:
  # PostgreSQL Database for local development (matches production)
  postgres:
    image: postgres:16-alpine
    container_name: hikehub-postgres
    environment:
      POSTGRES_USER: organiser_user
      POSTGRES_PASSWORD: organiser_pass
      POSTGRES_DB: organiser_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U organiser_user -d organiser_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
