services:
  - type: web
    name: hikehub-backend
    runtime: docker
    region: oregon # Free tier available
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
      - key: DATABASE_URL
        fromDatabase:
          name: hikehub-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: hikehub-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: hikehub-db
          property: password
      - key: JWT_SECRET
        generateValue: true
        # You can also set this manually in Render dashboard
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health
    autoDeploy: true

databases:
  - name: hikehub-db
    databaseName: hikehub
    region: oregon
    plan: free # 1GB storage, expires after 90 days (renewable)
    # PostgreSQL 15 by default
