services:
  - type: web
    name: hikehub-backend
    env: java
    region: oregon # Free tier available
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/platform-1.0.0.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
      - key: DATABASE_URL
        fromDatabase:
          name: hikehub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        # You can also set this manually in Render dashboard
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health
    autoDeploy: true

databases:
  - name: hikehub-db
    databaseName: hikehub
    region: oregon
    plan: free # 1GB storage, expires after 90 days (renewable)
    # PostgreSQL 15 by default
